include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - "lib/src/generated/*.dart"
    - "lib/generated/intl/*.dart"
    # Ignore vendored packages analyzed in their own context
    - "third_party/**"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
# linter:
#   rules:

